#Author: RAHUL VERMA
#Email:	 rahulvermag4@gmail.com
MODULE_NAME:=hello
KSRC_DIR:=/usr/src/linux-5.0.1
obj-m:= $(MODULE_NAME).o
PWD=$(shell pwd)

default:
	$(MAKE) -C $(KSRC_DIR) M=$(PWD) modules











